insert into employee(name, position, salary) values('Анна Иванова', 'генеральный директор', 120000);
insert into employee(name, position, salary) values('Алиса Петрова', 'менеджер', 90000);
insert into employee(name, position, salary) values('Александр Галактионов', 'системный аналитик', 95000);
insert into employee(name, position, salary) values('Данил Гатауллин', 'разработчик', 95000);
insert into employee(name, position, salary) values('Иван Захаров', 'разработчик', 95000);
insert into employee(name, position, salary) values('Елизавета Волкова', 'разработчик', 95000);
insert into employee(name, position, salary) values('Диана Галиуллина', 'финансовый директор', 100000);
insert into employee(name, position, salary) values('Камиль Ахметов', 'тимлид', 100000);
insert into employee(name, position, salary) values('Виктория Иванова', 'техлид', 100000);
insert into employee(name, position, salary) values('Влад Устюгов', 'тестировщик', 90000);
insert into employee(name, position, salary) values('Александр Шепс', 'дизайнер', 80000);
insert into employee(name, position, salary) values('Евгений Плющенко', 'специалист технической поддержки', 30000);
insert into employee(name, position, salary) values('Алина Загитова', 'специалист технической поддержки', 30000);
insert into employee(name, position, salary) values('Джим Керри','специалист технической поддержки', 30000);
insert into employee(name, position, salary) values('Юрий Гагарин', 'космонавт', 1000);
insert into employee(name, position, salary) values('Диппер Пайнс', 'уборщик', 15000);
insert into employee(name, position, salary) values('Роберт Паттинсон', 'креативный директор', 100000);
insert into employee(name, position, salary) values('Николай Валуев', 'дата-инженер', 100000);
insert into employee(name, position, salary) values('Джанни Родари', 'сеньор помидор', 20000);
insert into employee(name, position, salary) values('Искандер Валиев', 'модератор', 100000);

